# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello_world": "00_core.ipynb",
         "Ability": "01_magic.ipynb",
         "Character": "01_magic.ipynb",
         "Mage": "01_magic.ipynb",
         "Demon": "01_magic.ipynb"}

modules = ["core.py",
           "magic.py"]

doc_url = "https://asrishaheem.github.io/segmentation/"

git_url = "https://github.com/asrishaheem/segmentation/tree/master/"

def custom_doc_links(name): return None
